### ISSUE TITLE
where is TestAbnfObject？

### ISSUE THREAD

**Issue by Charltsing** [fabianoliver/VbProjectParser#1]
ProjectReferenceTests.cs

var x = new TestAbnfObject();

where is  TestAbnfObject??

**Comment by fabianoliver** [comment]
Hi Charltsing,

thanks for pointing this out. That was debug legacy code from a previous iteration of the ABNF toolkit that failed to sync properly for some reason. I've updated the repo, should build fine now.

For the record, there is no unit test to replace this for the current version yet, setting up a proper one for the actual ProjectStream will be a bit of work.
Should be very straightforward for some simple custom class/syntax though if needed; I'd suggest looking at VbProjectParser\Data\ProjectStream.cs and the classes in its ABNF folder to see how syntax definition as well as reading from/writing to a properly formatted string works.
