### ISSUE TITLE
Feature Request: Be able to open a VBAProject in a Word file

### ISSUE THREAD

**Issue by rogergmagnificentamazing** [fabianoliver/VbProjectParser#14]
I'd like to be able to open a Word document's VBA stream. Currently the code only supports Excel in the VbProject class.

I see two possible options for this. 

1) Make an overload VbProjectWord class that will inherit and keep the public signature of VbProject except will work with a Word File.

2) Add a static on the VbProject class such as VbProject.LoadWordDocumentVbProject(string pathToWordFile) that would open the Word File.

I think  option #1 fits in better with the current code when looking but I'm also not a fan of doing things such as opening files and other expected failures within a class constructor. It may also be nice if think in future would have app specific methods that would make sense on the VbProject class level.

Option #2 would have a static called but it is confusing with the current class that also has a constructors for both WorkbookPart and another for the fileFullPath which it assumes is to an Excel file.

I'm leaning toward coding up option #1 and then can review what looks like. 

thoughts?

**Comment by rogergmagnificentamazing** [comment]
I looked into #1 and I can't figure out a way to not make it a breaking change if I introduce a class hierarchy.

After reviewing and investigating some more I think the smallest change would be to add a new public overload to VBProject that would be a generic overload with information the caller can provide independent of the application file being openned.

public VbProject(OpenXmlPackage xmlPackage, VbaProjectPart vbaProjectPart, bool disposeXmlPackage)

This would allow a Word document to be opened with the code:

WordprocessingDocument wordprocessingDocument = WordprocessingDocument.Open(fileNameFullPath, true /* isEditable */);
 vbProject = new VbProject(wordprocessingDocument, 
                            wordprocessingDocument.MainDocumentPart.GetPartsOfType<VbaProjectPart>().SingleOrDefault(), true /* disposeXmlpackage */);
 vbaStorage = vbProject.AsVbaStorage()

**Comment by rogergmagnificentamazing** [comment]
Additional info: There is the existing overload that takes the vbaProjectPart.
 public VbProject(VbaProjectPart vbaProjectPart)
 
Maybe for now I should just use that passing in the Word VbaProjectpart and handle the lifetime of the word document xmlPackage making sure not to close until after have disposed of the VbProject. 

Example:
```
WordprocessingDocument wpDoc = WordprocessingDocument.Open(fileNameFullPath, true /* isEditable */);
vbProject = new VbProject(wpDoc.MainDocumentPart.GetPartsOfType<VbaProjectPart>().SingleOrDefault());

```
Please let me know thoughts; I'm leaning toward just retracting this feature request.

**Comment by rogergmagnificentamazing** [comment]
Closing feature request since have a way to open a Word Document's VBA stream with the existing code

**Comment by fabianoliver** [comment]
Thanks - glad you found an easy(ish) way to make it work for Word!

Generally, if in the future there's any structural differences between types across different apps, I definitely like the idea of inheritance. I think Roslyn might be a neat reference point there with its language-specific types (say CSharpCompilation vs VisualBasicCompilation). 

Similarly, definitely agree that loading up files from a constructor isn't the nicest thing to do - shame on past-me. A static factory method would be much nicer, even more so considering there probably should be an async overload as well.

So some form of VbProjectExcel and VbProjectWord inheriting from VbProject, each with their own static factory methods, might be a good idea in that case. As you say, bit of a breaking change in terms of the prior constructors on VbProject here, though I'd think that's accepptable if it becomes necessary in the future.

If there's no difference to differentiate between VbProjectExcel and VbProjectWord, it might also be possible to just infer the type of the application from the file in the existing constructor (maybe just via file extension, or by actually attempting to parse the file)
