### ISSUE TITLE
Unable to read VBA if contains a PROJECTCOMPATVERSION record.

### ISSUE THREAD

**Issue by rogergmagnificentamazing** [fabianoliver/VbProjectParser#2]
Newer versions of Vbproject code have a PROJECTCOMPATVERSION record that the current projectinformation code doesn't check for an will fail to read in the vba. See: https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-ovba/ed5d7ede-5d7d-4645-bba3-ddfd9bdc76ed

Minimal fix for this is to check for the existence of the record before checking for the PROJECTLCID. Another fix could be to instead of the code relying on the records in a specific order is to loop checking the record type and then calling the appropriate code based on the record type. Could also then skip unknown record types.

I'd also recommend upgrading the code to .net 4.8 since the .net built against is out of support
@fabianoliver - I can do separate pull requests for handing the projectcompatversion record and upgrading to .net 
 4.8 depending on your feedback on the best way to approach.

**Comment by fabianoliver** [comment]
Hi @rogergmagnificentamazing ,

Thanks for raising this. PRs for both a .NET version facelift, as well as the PROJECTCOMPATVERSION would be much appreciated. I've had had much chance to use this project myself lately anymore, but of course happy to have a look at PRs addressing this.

> Another fix could be to instead of the code relying on the records in a specific order is to loop checking the record type and then calling the appropriate code based on the record type. Could also then skip unknown record types.

That sounds very slightly preferential to me - if you find that difficult to wire up, just ignoring and/ore optionally parsing the new record sound perfectly fine to me as well. Ultimately, it's probably "just" a trade-off between reducing the chance of breaks in the future, vs. increasing the odds of possibly relevant future additions being "silently ignored", so I don't think either way is _definitely_ better here (aside from maybe introducing an option to toggle ignoring vs throwing on unknown sections - but no need to overcomplicate things). 

Thanks a lot,
Fabian

**Comment by rogergmagnificentamazing** [comment]
Ack. I am on holiday for a few weeks but will then try to put some pull requests together for you to review at your convenience.

**Comment by rogergmagnificentamazing** [comment]
proposed fixed with pull request: https://github.com/fabianoliver/VbProjectParser/pull/6

**Comment by rogergmagnificentamazing** [comment]
Fixed with pull request https://github.com/fabianoliver/VbProjectParser/pull/6
